### ISSUE TITLE
"Setting objects unmanaged" section issues

### ISSUE THREAD

**Issue by e-minguez** [openshift/cluster-version-operator#248]
* The cluster-network file is `0000_70_cluster-network-operator_03_daemonset.yaml`

* The `release-image/0000_07_cluster-network-operator_03_daemonset.yaml` file even if it says `daemonset` it is actually a deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-operator
  namespace: openshift-network-operator
```

* The patch complains because it seems to require a group as well (https://godoc.org/github.com/openshift/api/config/v1#ComponentOverride):

```
- op: add
  path: /spec/overrides
  value:
  - kind: Deployment
    group: apps                        <--------- This
    name: cluster-network-operator
    namespace: openshift-network-operator
    unmanaged: true
```
