### ISSUE TITLE
openshift/api <-> openshift/cluster-version-operator ClusterStatusConditionType mismatch

### ISSUE THREAD

**Issue by petrkotas** [openshift/cluster-version-operator#437]
**What happened**

When CVO reports failing cluster v4.4 it returns Failing condition e.g.:
```
conditions:
    - lastTransitionTime: "2020-08-12T07:08:36Z"
      message: Done applying 4.4.10
      status: "True"
      type: Available
    - lastTransitionTime: "2020-08-12T06:53:47Z"
      status: "False"
      type: Failing
    - lastTransitionTime: "2020-08-12T07:08:36Z"
      message: Cluster version is 4.4.10
      status: "False"
      type: Progressing
    - lastTransitionTime: "2020-08-12T07:08:57Z"
      message: The update channel has not been configured.
      reason: NoChannel
      status: "False"
      type: RetrievedUpdates
```

This is an expected state related to the code: https://github.com/openshift/cluster-version-operator/blob/release-4.4/pkg/cvo/status.go#L240

However, the openshift/api expects one of the states https://github.com/openshift/api/blob/release-4.4/config/v1/types_cluster_operator.go#L141:
```
	OperatorAvailable ClusterStatusConditionType = "Available"
	OperatorProgressing ClusterStatusConditionType = "Progressing"
	OperatorDegraded ClusterStatusConditionType = "Degraded"
	OperatorUpgradeable ClusterStatusConditionType = "Upgradeable"
```

**What you expected to happen**

openshift/cvo and openshift/api to have mathich conditions defined.
